### ISSUE TITLE
New UI for the app

### ISSUE THREAD

**Issue by phanindra-max** [phanindra-max/your-vivid-expressions#1]
Add a new User Interface to the canvas of the app.

Currently, it looks like this.
![ Current minimal UI ](https://user-images.githubusercontent.com/51989959/122710619-4c22e680-d27e-11eb-8486-001fd9bb95f0.jpg)

**_This should be an easy implementation if you're familiar with Canvas, CSS._**

Feel free to reach out if any doubts/queries.

**Comment by mindninjaX** [comment]
Well, it looks interesting! I would like to work on this ⭐

**Comment by phanindra-max** [comment]
Sure, go ahead and never hesitate to reach out if you have any doubts about the code 😃

Best of luck!😉

**Comment by mindninjaX** [comment]
Thanks @phanindra-max! I'll start working on this right away! Also consider assigning this issue to me so that others will know that I'm currently working on it.

**Comment by ishtiaqSamdani** [comment]
@mindninjaX  super update abba

**Comment by ishtiaqSamdani** [comment]
check the pr brah
![Screenshot (5)](https://user-images.githubusercontent.com/82057297/222129249-2d0be113-aa98-4790-a988-63d0d1d16876.png)
